FROM ubuntu:22.04

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
      git \
      build-essential \
      software-properties-common \
      ca-certificates \
      wget \
      curl \
      libgl1-mesa-glx

RUN apt-get update && apt-get install -y python3 python3-pip libgl1 && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    pip3 install --upgrade pip


RUN pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cpu
# install loadgen
RUN cd /tmp && \
    git clone --recursive https://github.com/pgmpablo157321/mlperf_automotive --branch verbose_run && \
    cd mlperf_automotive/loadgen && \
    pip install pybind11 && \
    CFLAGS="-std=c++14" python setup.py install && \
    rm -rf mlperf

RUN pip install numpy==1.26
RUN pip install onnx
RUN pip install onnxruntime
RUN pip install pillow
RUN pip install opencv-python
RUN pip install pyquaternion
RUN pip install tqdm
RUN pip install nuscenes-devkit
